### ISSUE TITLE
[Bug]: Dedicated server cannot launch, attempts to load ClientWorld class

### ISSUE THREAD

**Issue by sctjkc01** [Resourceful-Bees/ResourcefulBees#272]
### Bug Description

Attempting to load a dedicated server with Resourceful Bees on causes the server to fail to initialize, due to trying to load `net/minecraft/client/world/ClientWorld`.

### How to Reproduce?

1. Create a new dedicated server from Forge 36.2.0 with _just_ Resourceful Bees installed.
2. Launch the server (`java -jar forge-1.16.5-36.2.0.jar`)
3. Observe crash.

### Expected Behavior

Expected the server to load

### Version

0.9.9

### Mod Loader Version

1.16.5-36.2.0

### Logs or additional context

```[20:59:49] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Resourceful Bees (resourcefulbees) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.0.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.0.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.0.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.0.jar:?] {}
```

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Can you please provide the full log?

**Comment by sctjkc01** [comment]
My apologies.  [Here you go](https://pastebin.com/vkByiUsE).

**Comment by Epic428** [comment]
Gravy or dawn will have to look at it tonight or I’ll have to get it tomortow

**Comment by Vaerys-Dawn** [comment]
can you post your common.toml

**Comment by sctjkc01** [comment]
It should be the automatically generated default, but just in case: [here you are](https://pastebin.com/r48N7xZx).

**Comment by Epic428** [comment]
I don’t see what the Config has anything to do with the error. It crashes after loading the biome dictionary. So it’s whatever the next step in the load process is.

**Comment by Vaerys-Dawn** [comment]
the line it crashes on is the init for custom bee Data builder on the loading of apiary outputs at least in my build

**Comment by Vaerys-Dawn** [comment]
`at com.resourcefulbees.resourcefulbees.api.beedata.CustomBeeData$Builder.<init>(CustomBeeData.java:462) ~[resourcefulbees:1.16.5-0.9.9]`

**Comment by Vaerys-Dawn** [comment]
@sctjkc01 can you reproduce the error? does it happen every load

**Comment by Epic428** [comment]
Dawn can you run a server in IntelliJ and breakpoint where the crash occurs?

**Comment by Vaerys-Dawn** [comment]
can repro, now to see why this is happening

**Comment by Epic428** [comment]
Yeah gravy and I compared the last release and the code base Bc of the commit fiasco when we switched the main branch to arch. We couldn’t find anything that didn’t match so I’m just hoping we didn’t miss something.

**Comment by Vaerys-Dawn** [comment]
yeah i got nothing the debug doesn't make any sense

**Comment by Epic428** [comment]
Ooof. Strange. I’ll have to check it out tomorrow morning

**Comment by Epic428** [comment]
@sctjkc01 try downloading the update we pushed to curse and let us know if you still have an issue please.

**Comment by sctjkc01** [comment]
Apologies for the delay. Server with just RB 0.9.9.1 successfully launches!  👍
